Util#verify_xml should raise Saml::Errors::SignatureMissing when signed node is missing
Originally, "NoMethodError: undefined method `canonicalize' for nil:NilClass" had been raised.
It could reproduced when you've setup Google Workspace without "signed response" mode off.